const countryCodes = [
    { code: "+1", label: "USA/Canada" },
    { code: "+44", label: "UK" },
    { code: "+49", label: "Germany" },
    { code: "+91", label: "India" },
    { code: "+81", label: "Japan" },
    { code: "+61", label: "Australia" },
    { code: "+33", label: "France" },
    { code: "+39", label: "Italy" },
    { code: "+34", label: "Spain" },
    { code: "+86", label: "China" },
    { code: "+7", label: "Russia" },
    { code: "+55", label: "Brazil" },
    { code: "+27", label: "South Africa" },
    { code: "+82", label: "South Korea" },
    { code: "+31", label: "Netherlands" },
    { code: "+46", label: "Sweden" },
    { code: "+47", label: "Norway" },
    { code: "+45", label: "Denmark" },
    { code: "+48", label: "Poland" },
    { code: "+351", label: "Portugal" },
    { code: "+43", label: "Austria" },
    { code: "+32", label: "Belgium" },
    { code: "+52", label: "Mexico" },
    { code: "+54", label: "Argentina" },
    { code: "+63", label: "Philippines" },
    { code: "+62", label: "Indonesia" },
    { code: "+64", label: "New Zealand" },
    { code: "+20", label: "Egypt" },
    { code: "+234", label: "Nigeria" },
    { code: "+98", label: "Iran" },
    { code: "+90", label: "Turkey" },
    { code: "+94", label: "Sri Lanka" },
    { code: "+66", label: "Thailand" },
    { code: "+84", label: "Vietnam" },
    { code: "+60", label: "Malaysia" },
    { code: "+65", label: "Singapore" },
    { code: "+230", label: "Mauritius" },
    { code: "+351", label: "Portugal" },
    { code: "+94", label: "Sri Lanka" },
    { code: "+971", label: "United Arab Emirates" },
    { code: "+972", label: "Israel" },
    { code: "+27", label: "South Africa" },
    { code: "+373", label: "Moldova" },
    { code: "+357", label: "Cyprus" },
    { code: "+856", label: "Laos" },
    { code: "+380", label: "Ukraine" },
    { code: "+995", label: "Georgia" },
    { code: "+676", label: "Tonga" },
    { code: "+691", label: "Micronesia" },
    { code: "+373", label: "Moldova" },
    { code: "+212", label: "Morocco" },
    { code: "+233", label: "Ghana" },
    { code: "+51", label: "Peru" },
    { code: "+92", label: "Pakistan" },
    { code: "+593", label: "Ecuador" },
];

export default countryCodes